/*
Problem Description : (LC 389)
---------------------------------------------------------------------------
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
//Code:
//----------------------------------------------------------------------------------------------
class Solution {
public:
    char findTheDifference(string s, string t) {
        int arr[26] = {0};
        for(int i = 0 ; i < t.length() ; i++){
            arr[t[i]-'a']++;
            if(s[i]!='\0')
                arr[s[i]-'a']--;
        }
        char ans;
        for(int i = 0 ; i < 26 ; i++)
            if(arr[i]>0)
               ans = i+'a';
        return ans;
        
    }
};
